query getGlamp($glampId: Int) {
  glamp(glampId: $glampId) {
    id
    title
    description
    type
    price
    availableFrom
    availableTo
    adultCapacity
    childCapacity
    isLuxury
  }
}
